In [ ]:
import pandas as pd

In [15]:
sd=pd.DataFrame({
     "Salary":[1000,2000,3000,5000,7000,8000,9000,12000,50000]})
# quartile
median=sd["Salary"].quantile(0.50)
q1=sd["Salary"].quantile(0.25)
q3=sd["Salary"].quantile(0.75)


# IQR
iqr=q3-q1
lower_bound=q1-1.5*iqr
upper_bound=q3+1.5*iqr
upper_bound

18000.0

In [16]:
outlier=sd[(sd["Salary"]<lower_bound)|(sd["Salary"]>upper_bound)]
print(outlier)

   Salary
8   50000

In [8]:
dd=pd.read_csv("./dataset/bad_daraz_dataset.csv", )
# print(dd)
# print(dd.columns)
# print(dd.info())
# print(dd["price"].max())
# print(dd["price"].min())
# print(dd["price"].mean())
# print(dd[["product_name","product_id"]])
# print(dd.iloc[0]) first index ko lai tanyo
# print(dd.iloc[0:5])
# print(dd.iloc[0,7]) specific cell lai capture garxa
# print(dd.iloc[:,[2,4]]) 
# print(dd.loc[:,["product_name","product_id"]])
# print(dd.loc[dd["city"]=="Kathmandu"])
# print(dd.loc[(dd["city"] == "Kathmandu") & (dd["gender_target"] == "Male")])

In [34]:
bdd=pd.read_csv("./dataset/bad_daraz_dataset.csv")
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
12,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
13,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [8]:
# bdd.isnull().sum() NaN ,Null
# bdd.fillna(0) missing value ma 0 haldinye
# bdd["price"]=pd.to_numeric(bdd["price"],errors="coerce")
# bdd

In [7]:
# bdd["price"]=bdd["price"].fillna(bdd["price"].mean())
# bdd
# dummy=pd.Series(["100","200","abc"])
# pd.to_numeric(dummy,errors="coerce")

In [35]:
bdd["age"]=pd.to_numeric(bdd["age"],errors="coerce")
bdd["age"]=bdd["age"].fillna(bdd["age"].median())
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,16730.0,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,16730.0,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
9,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
10,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
11,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [6]:
# # bdd.dropna()
# # bdd[bdd.duplicated()]
# bdd["discount_percent"]=bdd["discount_percent"].str.replace("%","",regex=True)
# bdd

In [4]:
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [18]:
# bdd.duplicated().sum() hamro dataset ma kati ota dulication raixa vanna kura diya
bdd[bdd.duplicated()]

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
12,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [6]:
# bdd.duplicated("product_id") specific column ma find out garna sakinxa
# bdd.drop_duplicates(inplace=True) complete duplication data lai remove plus dataframe ma change/update garnye
bdd.drop_duplicates(subset="product_id",keep="first",inplace=True)
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
12,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [13]:
# negative fix and detect
bdd["price"]=pd.to_numeric(bdd["price"],errors="coerce")
bdd[bdd["price"]<0]
# bdd[bdd["rating"]>5]
bdd.loc[bdd["price"]<0,"price"]=0  #loc[row,column]
# bdd=bdd[bdd["price"]>0] #kunai pani negative or extra higher boundary vanda bahira ko lagi chai remove garera rw update garna 
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
12,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [40]:
# this is for inconsistence
# bdd["city"].str.strip()
# bdd["city"].str.rstrip() 
# bdd["city"].str.lower()
# bdd["city"].str.upper()
bdd["city"].str.title()

0       Kathmandu
1         Pokhara
2         Itahari
3      Biratnagar
4       Kathmandu
5         Pokhara
6       Kathmandu
7          Dharan
8       Kathmandu
9      Kathmandu
10     Kathmandu
11       Janakpur
12       Lalitpur
13       Lalitpur
Name: city, dtype: object

In [ ]:
# oulier detect and fix