In [2]:
import pandas as pd

In [18]:
dd=pd.read_csv("dataset/bad_daraz_dataset.csv")
dd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
12,12,Chair,Furniture,2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
13,12,Chair,Furniture,2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [19]:
dd["price"]=pd.to_numeric(dd["price"],errors="coerce")

# Quartile(q3),q1-->IQR

In [36]:
mean=dd["price"].mean()
std=dd["price"].std()
dd["z_score"]=(dd["price"]-mean)/std #z-score>2 outliers
outlier=dd[dd["z_score"].abs()>2]
outlier

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews,z_score
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80,2.270459

In [31]:
Q1=dd["price"].quantile(0.25)
Q3=dd["price"].quantile(0.75)
median=dd["price"].quantile(0.5)
IQR=Q3-Q1
lower_bound=Q1-(1.5*IQR)
upper_bound=Q3+(1.5*IQR)
upper_bound

7825.0

In [22]:
outlier=dd[(dd["price"]<lower_bound)| (dd["price"]>upper_bound)]
outlier

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120

In [25]:
len(outlier)

2

In [33]:
dd.loc[(dd["price"]<lower_bound)|(dd["price"]>upper_bound)]=median
dd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,2500,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,2500,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500
7,8,Bag,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
12,12,Chair,Furniture,2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
13,12,Chair,Furniture,2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [26]:
# IQR fix
# winsorization method
dd["price"].clip(lower_bound,upper_bound)

0     7825.0
1        NaN
2     3500.0
3     1500.0
4     5500.0
5     4200.0
6     7825.0
7        NaN
8     1800.0
9     2500.0
10    2500.0
11     800.0
12    2500.0
13    2500.0
Name: price, dtype: float64

In [ ]:
# SD=>kate deviate bako xa banyerwa tha hunxa
# Z-score method
 # formuala
# z-score=dd["price"]-mean